import type { Patient } from './types'

export const patients: Patient[] = [
  {
    id: 'P001',
    name: 'Priya Devi',
    age: 28,
    gender: 'Female',
    village: 'Rampur Kalan',
    district: 'Sitapur',
    state: 'Uttar Pradesh',
    phone: '9876543210',
    condition: 'Skin Infection',
    symptoms: ['Redness', 'Swelling', 'Itching', 'Warmth'],
    duration: 7,
    severity: 'Moderate',
    aiDiagnosis: { disease: 'Bacterial Skin Infection', confidence: 87 },
    status: 'Active',
    uploadedAt: '2026-04-10T08:30:00Z',
    ashaWorker: 'Rekha Verma',
    images: [
      { date: '2026-04-10', score: 5.5, label: 'Initial upload' },
      { date: '2026-04-11', score: 6.0, label: 'Day 2 – Worsening' },
      { date: '2026-04-12', score: 5.8, label: 'Day 3' },
      { date: '2026-04-13', score: 5.2, label: 'Day 4 – Improving' },
    ],
  },
  {
    id: 'P002',
    name: 'Rajan Kumar',
    age: 45,
    gender: 'Male',
    village: 'Barauli',
    district: 'Barabanki',
    state: 'Uttar Pradesh',
    phone: '9765432109',
    condition: 'Deep Wound',
    symptoms: ['Open wound', 'Pus discharge', 'High fever', 'Severe pain', 'Spreading redness'],
    duration: 12,
    severity: 'Severe',
    aiDiagnosis: { disease: 'Infected Deep Laceration', confidence: 92 },
    status: 'Escalated',
    uploadedAt: '2026-04-08T10:15:00Z',
    ashaWorker: 'Sunita Yadav',
    doctorNotes: 'Requires immediate IV antibiotics. Possible early sepsis. Refer to district hospital.',
    doctorDiagnosis: 'Infected deep laceration with spreading cellulitis',
    images: [
      { date: '2026-04-08', score: 7.5, label: 'Initial upload' },
      { date: '2026-04-09', score: 8.2, label: 'Day 2 – Deteriorating' },
      { date: '2026-04-10', score: 8.8, label: 'Day 3 – Critical' },
      { date: '2026-04-11', score: 8.5, label: 'Day 4 – Post treatment' },
      { date: '2026-04-12', score: 7.8, label: 'Day 5 – Responding' },
    ],
  },
  {
    id: 'P003',
    name: 'Meena Patel',
    age: 32,
    gender: 'Female',
    village: 'Khargone',
    district: 'Khargone',
    state: 'Madhya Pradesh',
    phone: '9654321098',
    condition: 'Skin Rash',
    symptoms: ['Itching', 'Red patches', 'Dry skin'],
    duration: 3,
    severity: 'Early',
    aiDiagnosis: { disease: 'Atopic Dermatitis', confidence: 78 },
    status: 'Active',
    uploadedAt: '2026-04-12T11:00:00Z',
    ashaWorker: 'Rekha Verma',
    images: [
      { date: '2026-04-12', score: 3.2, label: 'Initial upload' },
      { date: '2026-04-13', score: 2.9, label: 'Day 2 – Improving' },
    ],
  },
  {
    id: 'P004',
    name: 'Suresh Singh',
    age: 55,
    gender: 'Male',
    village: 'Bamori',
    district: 'Shivpuri',
    state: 'Madhya Pradesh',
    phone: '9543210987',
    condition: 'Diabetic Foot Ulcer',
    symptoms: ['Non-healing wound', 'Tissue blackening', 'Swelling', 'Loss of sensation', 'Odor'],
    duration: 21,
    severity: 'Severe',
    aiDiagnosis: { disease: 'Diabetic Foot Ulcer (Stage 3)', confidence: 95 },
    status: 'Escalated',
    uploadedAt: '2026-04-05T09:00:00Z',
    ashaWorker: 'Geeta Rani',
    doctorNotes: 'Urgent surgical consultation needed. Risk of amputation if not treated immediately.',
    doctorDiagnosis: 'Diabetic foot ulcer with peripheral vascular disease',
    images: [
      { date: '2026-04-05', score: 8.0, label: 'Initial upload' },
      { date: '2026-04-07', score: 8.5, label: 'Day 3' },
      { date: '2026-04-09', score: 9.0, label: 'Day 5 – Worsening' },
      { date: '2026-04-11', score: 9.2, label: 'Day 7 – Critical' },
      { date: '2026-04-13', score: 8.8, label: 'Day 9 – Post treatment' },
    ],
  },
  {
    id: 'P005',
    name: 'Anita Sharma',
    age: 22,
    gender: 'Female',
    village: 'Daltonganj',
    district: 'Palamau',
    state: 'Jharkhand',
    phone: '9432109876',
    condition: 'Contact Dermatitis',
    symptoms: ['Itching', 'Mild redness', 'Small blisters'],
    duration: 2,
    severity: 'Early',
    aiDiagnosis: { disease: 'Contact Dermatitis', confidence: 82 },
    status: 'Active',
    uploadedAt: '2026-04-13T07:45:00Z',
    ashaWorker: 'Priya Singh',
    images: [
      { date: '2026-04-13', score: 2.8, label: 'Initial upload' },
    ],
  },
  {
    id: 'P006',
    name: 'Mahesh Yadav',
    age: 38,
    gender: 'Male',
    village: 'Multai',
    district: 'Betul',
    state: 'Madhya Pradesh',
    phone: '9321098765',
    condition: 'Fungal Infection',
    symptoms: ['Ring-shaped patches', 'Scaly skin', 'Itching', 'Hair loss in patches'],
    duration: 14,
    severity: 'Moderate',
    aiDiagnosis: { disease: 'Tinea Corporis (Ringworm)', confidence: 89 },
    status: 'Active',
    uploadedAt: '2026-04-09T14:20:00Z',
    ashaWorker: 'Geeta Rani',
    images: [
      { date: '2026-04-09', score: 5.0, label: 'Initial upload' },
      { date: '2026-04-10', score: 5.3, label: 'Day 2' },
      { date: '2026-04-11', score: 5.1, label: 'Day 3' },
      { date: '2026-04-12', score: 4.8, label: 'Day 4 – Improving' },
      { date: '2026-04-13', score: 4.5, label: 'Day 5' },
    ],
  },
  {
    id: 'P007',
    name: 'Kamla Devi',
    age: 50,
    gender: 'Female',
    village: 'Niwas',
    district: 'Mandla',
    state: 'Madhya Pradesh',
    phone: '9210987654',
    condition: 'Burn Wound',
    symptoms: ['Large burn area', 'Blistering', 'Extreme pain', 'Weeping wound', 'High fever'],
    duration: 5,
    severity: 'Severe',
    aiDiagnosis: { disease: 'Second Degree Burns (>10% BSA)', confidence: 91 },
    status: 'Escalated',
    uploadedAt: '2026-04-11T16:30:00Z',
    ashaWorker: 'Sunita Yadav',
    doctorNotes: 'Transferred to burn unit. Requires fluid resuscitation and daily dressing changes.',
    doctorDiagnosis: 'Second degree burns covering ~15% body surface area',
    images: [
      { date: '2026-04-11', score: 8.5, label: 'Initial upload' },
      { date: '2026-04-12', score: 8.8, label: 'Day 2 – Worsening' },
      { date: '2026-04-13', score: 8.0, label: 'Day 3 – Post treatment' },
    ],
  },
  {
    id: 'P008',
    name: 'Ramesh Gupta',
    age: 42,
    gender: 'Male',
    village: 'Naraini',
    district: 'Banda',
    state: 'Uttar Pradesh',
    phone: '9109876543',
    condition: 'Heat Rash',
    symptoms: ['Small red bumps', 'Mild itching', 'Tingling sensation'],
    duration: 4,
    severity: 'Early',
    aiDiagnosis: { disease: 'Miliaria Rubra (Heat Rash)', confidence: 76 },
    status: 'Resolved',
    uploadedAt: '2026-04-07T09:00:00Z',
    ashaWorker: 'Rekha Verma',
    images: [
      { date: '2026-04-07', score: 2.5, label: 'Initial upload' },
      { date: '2026-04-09', score: 2.0, label: 'Day 3 – Improving' },
      { date: '2026-04-11', score: 1.5, label: 'Day 5 – Nearly clear' },
      { date: '2026-04-13', score: 1.0, label: 'Day 7 – Resolved' },
    ],
  },
  {
    id: 'P009',
    name: 'Savita Kumari',
    age: 19,
    gender: 'Female',
    village: 'Indergarh',
    district: 'Datia',
    state: 'Madhya Pradesh',
    phone: '9098765432',
    condition: 'Scalp Condition',
    symptoms: ['Flaky scalp', 'Oily patches', 'Mild redness', 'Itching'],
    duration: 10,
    severity: 'Moderate',
    aiDiagnosis: { disease: 'Seborrheic Dermatitis', confidence: 83 },
    status: 'Active',
    uploadedAt: '2026-04-10T12:00:00Z',
    ashaWorker: 'Priya Singh',
    images: [
      { date: '2026-04-10', score: 4.5, label: 'Initial upload' },
      { date: '2026-04-11', score: 4.8, label: 'Day 2' },
      { date: '2026-04-12', score: 4.6, label: 'Day 3' },
      { date: '2026-04-13', score: 4.2, label: 'Day 4 – Improving' },
    ],
  },
  {
    id: 'P010',
    name: 'Dinesh Patel',
    age: 60,
    gender: 'Male',
    village: 'Patharia',
    district: 'Damoh',
    state: 'Madhya Pradesh',
    phone: '8987654321',
    condition: 'Skin Abscess',
    symptoms: ['Large painful lump', 'Pus formation', 'High fever', 'Severe tenderness', 'Swelling'],
    duration: 8,
    severity: 'Severe',
    aiDiagnosis: { disease: 'Cutaneous Abscess', confidence: 94 },
    status: 'Active',
    uploadedAt: '2026-04-09T08:00:00Z',
    ashaWorker: 'Geeta Rani',
    images: [
      { date: '2026-04-09', score: 7.0, label: 'Initial upload' },
      { date: '2026-04-10', score: 7.5, label: 'Day 2 – Growing' },
      { date: '2026-04-11', score: 8.0, label: 'Day 3 – Critical' },
      { date: '2026-04-12', score: 8.2, label: 'Day 4' },
      { date: '2026-04-13', score: 7.8, label: 'Day 5' },
    ],
  },
  {
    id: 'P011',
    name: 'Lalita Bai',
    age: 35,
    gender: 'Female',
    village: 'Sausar',
    district: 'Chhindwara',
    state: 'Madhya Pradesh',
    phone: '8876543210',
    condition: 'Ringworm',
    symptoms: ['Circular rash', 'Scaly border', 'Itching'],
    duration: 5,
    severity: 'Early',
    aiDiagnosis: { disease: 'Tinea Cruris (Ringworm)', confidence: 85 },
    status: 'Active',
    uploadedAt: '2026-04-11T10:30:00Z',
    ashaWorker: 'Sunita Yadav',
    images: [
      { date: '2026-04-11', score: 3.0, label: 'Initial upload' },
      { date: '2026-04-12', score: 2.8, label: 'Day 2' },
      { date: '2026-04-13', score: 2.5, label: 'Day 3 – Improving' },
    ],
  },
  {
    id: 'P012',
    name: 'Mohan Lal',
    age: 48,
    gender: 'Male',
    village: 'Sabalgarh',
    district: 'Morena',
    state: 'Madhya Pradesh',
    phone: '8765432109',
    condition: 'Cellulitis',
    symptoms: ['Expanding red area', 'Warmth', 'Tenderness', 'Swelling', 'Mild fever'],
    duration: 6,
    severity: 'Moderate',
    aiDiagnosis: { disease: 'Non-purulent Cellulitis', confidence: 88 },
    status: 'Active',
    uploadedAt: '2026-04-10T15:00:00Z',
    ashaWorker: 'Priya Singh',
    images: [
      { date: '2026-04-10', score: 5.5, label: 'Initial upload' },
      { date: '2026-04-11', score: 5.8, label: 'Day 2 – Spreading' },
      { date: '2026-04-12', score: 5.6, label: 'Day 3' },
      { date: '2026-04-13', score: 5.2, label: 'Day 4 – Improving' },
    ],
  },
  {
    id: 'P013',
    name: 'Pushpa Rani',
    age: 27,
    gender: 'Female',
    village: 'Vijaypur',
    district: 'Sheopur',
    state: 'Madhya Pradesh',
    phone: '8654321098',
    condition: 'Infected Burn',
    symptoms: ['Burn wound with infection', 'Greenish discharge', 'High fever', 'Severe pain', 'Foul odor'],
    duration: 9,
    severity: 'Severe',
    aiDiagnosis: { disease: 'Infected Thermal Burn', confidence: 96 },
    status: 'Escalated',
    uploadedAt: '2026-04-07T11:00:00Z',
    ashaWorker: 'Geeta Rani',
    doctorNotes: 'Pseudomonas suspected. Culture sent. Starting targeted antibiotic therapy.',
    doctorDiagnosis: 'Infected second degree burn with septic signs',
    images: [
      { date: '2026-04-07', score: 7.8, label: 'Initial upload' },
      { date: '2026-04-09', score: 8.5, label: 'Day 3 – Infected' },
      { date: '2026-04-11', score: 9.0, label: 'Day 5 – Severe' },
      { date: '2026-04-12', score: 8.8, label: 'Day 6 – Treatment started' },
      { date: '2026-04-13', score: 8.2, label: 'Day 7 – Responding' },
    ],
  },
  {
    id: 'P014',
    name: 'Vijay Singh',
    age: 33,
    gender: 'Male',
    village: 'Lakhnadon',
    district: 'Seoni',
    state: 'Madhya Pradesh',
    phone: '8543210987',
    condition: 'Insect Bite Reaction',
    symptoms: ['Localized swelling', 'Redness', 'Mild pain', 'Small welt'],
    duration: 3,
    severity: 'Early',
    aiDiagnosis: { disease: 'Hymenoptera Sting Reaction', confidence: 72 },
    status: 'Resolved',
    uploadedAt: '2026-04-09T13:00:00Z',
    ashaWorker: 'Rekha Verma',
    images: [
      { date: '2026-04-09', score: 2.2, label: 'Initial upload' },
      { date: '2026-04-11', score: 1.5, label: 'Day 3 – Reducing' },
      { date: '2026-04-13', score: 0.8, label: 'Day 5 – Resolved' },
    ],
  },
  {
    id: 'P015',
    name: 'Geeta Devi',
    age: 44,
    gender: 'Female',
    village: 'Hanumana',
    district: 'Rewa',
    state: 'Madhya Pradesh',
    phone: '8432109876',
    condition: 'Diabetic Wound',
    symptoms: ['Chronic non-healing wound', 'Tissue necrosis', 'Discharge', 'Neuropathy pain', 'Swelling'],
    duration: 30,
    severity: 'Severe',
    aiDiagnosis: { disease: 'Diabetic Wound Infection (Wagner Grade 2)', confidence: 93 },
    status: 'Active',
    uploadedAt: '2026-04-03T09:30:00Z',
    ashaWorker: 'Sunita Yadav',
    images: [
      { date: '2026-04-03', score: 7.5, label: 'Initial upload' },
      { date: '2026-04-05', score: 7.8, label: 'Day 3' },
      { date: '2026-04-07', score: 8.0, label: 'Day 5' },
      { date: '2026-04-09', score: 8.3, label: 'Day 7 – Worsening' },
      { date: '2026-04-11', score: 8.5, label: 'Day 9' },
      { date: '2026-04-13', score: 8.2, label: 'Day 11 – Slight improvement' },
    ],
  },
  {
    id: 'P016',
    name: 'Arun Sharma',
    age: 29,
    gender: 'Male',
    village: 'Maihar',
    district: 'Satna',
    state: 'Madhya Pradesh',
    phone: '8321098765',
    condition: 'Psoriasis',
    symptoms: ['Silver-scaled plaques', 'Thick red patches', 'Itching', 'Cracking skin'],
    duration: 20,
    severity: 'Moderate',
    aiDiagnosis: { disease: 'Plaque Psoriasis', confidence: 86 },
    status: 'Active',
    uploadedAt: '2026-04-06T14:00:00Z',
    ashaWorker: 'Priya Singh',
    images: [
      { date: '2026-04-06', score: 5.8, label: 'Initial upload' },
      { date: '2026-04-08', score: 5.5, label: 'Day 3 – Improving' },
      { date: '2026-04-10', score: 5.2, label: 'Day 5' },
      { date: '2026-04-12', score: 4.9, label: 'Day 7' },
    ],
  },
  {
    id: 'P017',
    name: 'Radha Kumari',
    age: 52,
    gender: 'Female',
    village: 'Ajaygarh',
    district: 'Panna',
    state: 'Madhya Pradesh',
    phone: '8210987654',
    condition: 'Scabies',
    symptoms: ['Intense nighttime itching', 'Burrow tracks', 'Pimple-like rash', 'Blisters'],
    duration: 8,
    severity: 'Early',
    aiDiagnosis: { disease: 'Scabies (Sarcoptes scabiei)', confidence: 81 },
    status: 'Active',
    uploadedAt: '2026-04-09T16:00:00Z',
    ashaWorker: 'Geeta Rani',
    images: [
      { date: '2026-04-09', score: 3.5, label: 'Initial upload' },
      { date: '2026-04-10', score: 3.8, label: 'Day 2' },
      { date: '2026-04-11', score: 3.5, label: 'Day 3' },
      { date: '2026-04-12', score: 3.2, label: 'Day 4 – After medication' },
      { date: '2026-04-13', score: 2.8, label: 'Day 5 – Improving' },
    ],
  },
  {
    id: 'P018',
    name: 'Bharat Kumar',
    age: 36,
    gender: 'Male',
    village: 'Tendukheda',
    district: 'Narsinghpur',
    state: 'Madhya Pradesh',
    phone: '8109876543',
    condition: 'Post-Surgical Wound',
    symptoms: ['Wound dehiscence', 'Purulent discharge', 'High fever', 'Severe pain', 'Surrounding redness'],
    duration: 15,
    severity: 'Severe',
    aiDiagnosis: { disease: 'Surgical Site Infection (SSI)', confidence: 97 },
    status: 'Escalated',
    uploadedAt: '2026-04-04T10:00:00Z',
    ashaWorker: 'Rekha Verma',
    doctorNotes: 'MRSA suspected. Wound cultures sent. Vancomycin initiated. May require return to theatre.',
    doctorDiagnosis: 'Deep incisional surgical site infection – possible MRSA',
    images: [
      { date: '2026-04-04', score: 7.2, label: 'Initial upload' },
      { date: '2026-04-06', score: 8.0, label: 'Day 3 – Worsening' },
      { date: '2026-04-08', score: 8.5, label: 'Day 5 – Dehiscence' },
      { date: '2026-04-10', score: 9.0, label: 'Day 7 – Severe' },
      { date: '2026-04-12', score: 8.5, label: 'Day 9 – Post treatment' },
    ],
  },
  {
    id: 'P019',
    name: 'Sunita Devi',
    age: 24,
    gender: 'Female',
    village: 'Murwara',
    district: 'Katni',
    state: 'Madhya Pradesh',
    phone: '8009876543',
    condition: 'Prickly Heat',
    symptoms: ['Small red bumps', 'Stinging sensation', 'Mild swelling', 'Rash in skin folds'],
    duration: 5,
    severity: 'Early',
    aiDiagnosis: { disease: 'Miliaria Crystallina (Prickly Heat)', confidence: 74 },
    status: 'Resolved',
    uploadedAt: '2026-04-06T08:00:00Z',
    ashaWorker: 'Priya Singh',
    images: [
      { date: '2026-04-06', score: 2.0, label: 'Initial upload' },
      { date: '2026-04-08', score: 1.5, label: 'Day 3 – Improving' },
      { date: '2026-04-10', score: 1.0, label: 'Day 5 – Nearly resolved' },
      { date: '2026-04-12', score: 0.5, label: 'Day 7 – Resolved' },
    ],
  },
  {
    id: 'P020',
    name: 'Rajendra Prasad',
    age: 67,
    gender: 'Male',
    village: 'Rampur Naikin',
    district: 'Sidhi',
    state: 'Madhya Pradesh',
    phone: '7987654321',
    condition: 'Venous Leg Ulcer',
    symptoms: ['Large open ulcer', 'Weeping wound', 'Varicose veins', 'Leg swelling', 'Dark skin discoloration'],
    duration: 45,
    severity: 'Severe',
    aiDiagnosis: { disease: 'Chronic Venous Leg Ulcer', confidence: 91 },
    status: 'Active',
    uploadedAt: '2026-04-01T11:00:00Z',
    ashaWorker: 'Sunita Yadav',
    images: [
      { date: '2026-04-01', score: 8.0, label: 'Initial upload' },
      { date: '2026-04-04', score: 8.2, label: 'Day 4' },
      { date: '2026-04-07', score: 8.5, label: 'Day 7 – Worsening' },
      { date: '2026-04-10', score: 8.3, label: 'Day 10 – Stabilising' },
      { date: '2026-04-13', score: 8.0, label: 'Day 13' },
    ],
  },
]

export const ashaWorkers = ['Rekha Verma', 'Sunita Yadav', 'Priya Singh', 'Geeta Rani']

export const karnatakaDistricts = [
  'Bagalkot', 'Ballari', 'Belagavi', 'Bengaluru Rural', 'Bengaluru Urban',
  'Bidar', 'Chamarajanagar', 'Chikkaballapur', 'Chikkamagaluru', 'Chitradurga',
  'Dakshina Kannada', 'Davanagere', 'Dharwad', 'Gadag', 'Hassan',
  'Haveri', 'Kalaburagi', 'Kodagu', 'Kolar', 'Koppal',
  'Mandya', 'Mysuru', 'Raichur', 'Ramanagara', 'Shivamogga',
  'Tumakuru', 'Udupi', 'Uttara Kannada', 'Vijayapura', 'Yadgir',
]

export const symptomsList = [
  'Redness', 'Swelling', 'Itching', 'Pain', 'Fever', 'Pus discharge',
  'Open wound', 'Blistering', 'Scaly skin', 'Dry skin', 'Burning sensation',
  'Warmth', 'Tenderness', 'Rash', 'Discoloration', 'Odor', 'Numbness',
  'Bleeding', 'Crusting', 'Weeping', 'Hair loss', 'Peeling',
]
